"""add fields deadline_percents

Revision ID: 034ca49fdb7c
Revises: 875018514d03
Create Date: 2022-12-18 18:04:58.171405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034ca49fdb7c'
down_revision = '875018514d03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('deadline_25_percent', sa.String(length=1), nullable=True))
    op.add_column('tasks', sa.Column('deadline_50_percent', sa.String(length=1), nullable=True))
    op.add_column('tasks', sa.Column('deadline_75_percent', sa.String(length=1), nullable=True))
    op.add_column('tasks', sa.Column('deadline_100_percent', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'deadline_100_percent')
    op.drop_column('tasks', 'deadline_75_percent')
    op.drop_column('tasks', 'deadline_50_percent')
    op.drop_column('tasks', 'deadline_25_percent')
    # ### end Alembic commands ###
