"""add field is_send_email in table users

Revision ID: 1b4099067cd1
Revises: 034ca49fdb7c
Create Date: 2023-03-28 22:11:26.948683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b4099067cd1'
down_revision = '034ca49fdb7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_send_email', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_send_email')
    # ### end Alembic commands ###
