"""add field period in table tasks

Revision ID: 2d6aef805a46
Revises: 9c789ffda8ed
Create Date: 2022-09-11 19:50:09.160030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d6aef805a46'
down_revision = '9c789ffda8ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('period', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'period')
    # ### end Alembic commands ###
