"""add field deadline_today in table tasks

Revision ID: 5d9dc9583c50
Revises: 3f842b9c5cb7
Create Date: 2023-08-10 11:34:30.839275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d9dc9583c50'
down_revision = '3f842b9c5cb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('deadline_today', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'deadline_today')
    # ### end Alembic commands ###
