"""add table subscription

Revision ID: 6ef77cfafe66
Revises: afe899261403
Create Date: 2022-09-03 20:15:02.997582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef77cfafe66'
down_revision = 'afe899261403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_users', sa.Integer(), nullable=True),
    sa.Column('push_param', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['id_users'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_id'), 'subscription', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_id'), table_name='subscription')
    op.drop_table('subscription')
    # ### end Alembic commands ###
