"""add field period_type

Revision ID: 875018514d03
Revises: b733a7e30fc2
Create Date: 2022-10-08 23:21:16.995436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875018514d03'
down_revision = 'b733a7e30fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('period_type', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'period_type')
    # ### end Alembic commands ###
