"""add field url_photo in table users

Revision ID: 9c789ffda8ed
Revises: fce2f8348f19
Create Date: 2022-09-10 19:30:16.040873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c789ffda8ed'
down_revision = 'fce2f8348f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('url_photo', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'url_photo')
    # ### end Alembic commands ###
