"""add field period_type in table tasks

Revision ID: aa6b49c72939
Revises: b733a7e30fc2
Create Date: 2022-10-08 20:30:46.012983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa6b49c72939'
down_revision = 'b733a7e30fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('period_type', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'period_type')
    # ### end Alembic commands ###
