"""add table complexity and field complexity in table tasks

Revision ID: afe899261403
Revises: c841a769a625
Create Date: 2022-08-18 19:25:39.852846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe899261403'
down_revision = 'c841a769a625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complexity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_complexity_id'), 'complexity', ['id'], unique=False)
    op.add_column('tasks', sa.Column('id_complexity', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'complexity', ['id_complexity'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'id_complexity')
    op.drop_index(op.f('ix_complexity_id'), table_name='complexity')
    op.drop_table('complexity')
    # ### end Alembic commands ###
