"""add table subtasks

Revision ID: b733a7e30fc2
Revises: 2d6aef805a46
Create Date: 2022-09-12 21:27:30.182212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b733a7e30fc2'
down_revision = '2d6aef805a46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtasks',
    sa.Column('id_task', sa.Integer(), nullable=True),
    sa.Column('id_subtask', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_subtask'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['id_task'], ['tasks.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subtasks')
    # ### end Alembic commands ###
