"""add field date_completion table in tasks

Revision ID: c841a769a625
Revises: da992f0aacc9
Create Date: 2022-08-16 21:07:05.194091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c841a769a625'
down_revision = 'da992f0aacc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('date_completion', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'date_completion')
    # ### end Alembic commands ###
