"""add field, add index in table tasks

Revision ID: da992f0aacc9
Revises: 375efe166af7
Create Date: 2022-08-14 12:22:54.576375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da992f0aacc9'
down_revision = '375efe166af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('create_user', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_id_status'), 'tasks', ['id_status'], unique=False)
    op.create_foreign_key(None, 'tasks', 'users', ['create_user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_id_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_column('tasks', 'create_date')
    op.drop_column('tasks', 'create_user')
    # ### end Alembic commands ###
