"""add field token in table subscription

Revision ID: fd53c1e40bce
Revises: b733a7e30fc2
Create Date: 2022-09-29 21:03:11.948884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd53c1e40bce'
down_revision = 'b733a7e30fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('token_hash', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'token_hash')
    # ### end Alembic commands ###
